services:
  server:
    image: ghcr.io/ssokurenko/fullstack-typescript-iot-server:latest
    ports:
      - "4000:4000"
      - "4001:4001"

  client:
    image: ghcr.io/ssokurenko/fullstack-typescript-iot-client:latest
    ports:
      - "8080:80"
    depends_on:
      - server

  mock-device:
    image: ghcr.io/ssokurenko/fullstack-typescript-iot-mock-device:latest
    profiles: ["demo"]
    environment:
      MOCK_TARGET_URL: http://server:4000/readings
    depends_on:
      - server
